from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class FoodAtlas(db.Model):
    __tablename__ = 'food_atlas'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    fips = db.Column(db.Integer, unique=True, nullable=False)
    county = db.Column(db.String(255))
    state = db.Column(db.String(255))
    pct_laccess_pop15 = db.Column(db.Float)
    pct_laccess_lowi15 = db.Column(db.Float)
    pct_laccess_hhnv15 = db.Column(db.Float)
    pct_laccess_snap15 = db.Column(db.Float)
    pct_laccess_child15 = db.Column(db.Float)
    pct_laccess_seniors15 = db.Column(db.Float)
    pct_laccess_white15 = db.Column(db.Float)
    pct_laccess_black15 = db.Column(db.Float)
    pct_laccess_hisp15 = db.Column(db.Float)
    pct_laccess_nhasian15 = db.Column(db.Float)
    pct_laccess_nhna15 = db.Column(db.Float)
    pct_laccess_nhpi15 = db.Column(db.Float)
    pct_laccess_multir15 = db.Column(db.Float)
    grocpth14 = db.Column(db.Float)
    supercpth14 = db.Column(db.Float)
    convspth14 = db.Column(db.Float)
    specspth14 = db.Column(db.Float)
    snapspth16 = db.Column(db.Float)
    ffrpth14 = db.Column(db.Float)
    fsrpth14 = db.Column(db.Float)
    pct_snap16 = db.Column(db.Float)
    pct_nslp15 = db.Column(db.Float)
    pct_sbp15 = db.Column(db.Float)
    pct_sfsp15 = db.Column(db.Float)
    pct_wic15 = db.Column(db.Float)
    sodatax_stores14 = db.Column(db.Float)
    sodatax_vendm14 = db.Column(db.Float)
    chipstax_stores14 = db.Column(db.Float)
    chipstax_vendm14 = db.Column(db.Float)
    food_tax14 = db.Column(db.Float)
    fmrktpth16 = db.Column(db.Float)
    pct_fmrkt_snap16 = db.Column(db.Float)
    pct_fmrkt_wic16 = db.Column(db.Float)
    pct_fmrkt_wiccash16 = db.Column(db.Float)
    pct_fmrkt_sfmnp16 = db.Column(db.Float)
    pct_fmrkt_credit16 = db.Column(db.Float)
    pct_fmrkt_frveg16 = db.Column(db.Float)
    pct_fmrkt_anmlprod16 = db.Column(db.Float)
    pct_fmrkt_baked16 = db.Column(db.Float)
    pct_fmrkt_otherfood16 = db.Column(db.Float)
    foodhub16 = db.Column(db.Integer)
    pct_diabetes_adults13 = db.Column(db.Float)
    pct_obese_adults13 = db.Column(db.Float)
    pct_hspa15 = db.Column(db.Float)
    recfacpth14 = db.Column(db.Float)
    pct_nhwhite10 = db.Column(db.Float)
    pct_nhblack10 = db.Column(db.Float)
    pct_hisp10 = db.Column(db.Float)
    pct_nhasian10 = db.Column(db.Float)
    pct_nhna10 = db.Column(db.Float)
    pct_nhpi10 = db.Column(db.Float)
    pct_65older10 = db.Column(db.Float)
    pct_18younger10 = db.Column(db.Float)
    medhhinc15 = db.Column(db.Float)
    povrate15 = db.Column(db.Float)
    metro13 = db.Column(db.Boolean)
